variables:
    IMAGE_NAME: jainsiddharth1999/zeltatech
    IMAGE_TAG: $CI_PROJECT_ID
    CONTAINER_NAME: $CI_PROJECT_NAME

stages:
  - deploy

deploy:
  only:
    - main  
  stage: deploy
  
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $SERVER
    - docker rmi $IMAGE_NAME:$IMAGE_TAG 
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
    - docker stop $CONTAINER_NAME || true &&
    - docker rm $CONTAINER_NAME || true &&
    - docker run  -dit --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG



